version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - db

  scraper:
    build:
      context: .
      dockerfile: src/scraper/Dockerfile
    depends_on:
      - backend
    restart: on-failure
    entrypoint: ['sh', '/app/start-scrapper.sh', 'backend', '3000']

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
